import type { BlogPost } from './types';
import { legacyBlogImages } from './stock-images';

/** Метадані 15 статей з Blog/BlogPost1–15.jsx */
export const legacyBlogMeta: BlogPost[] = [
  {
    slug: 'yak-stvoryty-telegram-bota',
    legacyId: 1,
    category: 'telegram',
    publishedAt: '2025-11-01',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 18,
    image: legacyBlogImages[1],
    imageAlt: 'Мінімалістичне робоче місце з кодом на екрані монітора',
    relatedSlugs: ['telegram-bot-dlya-biznesu-2026', 'skilky-koshtuye-telegram-bot', 'rozrobka-telegram-botiv-vid-ideyi'],
    seoTitle: 'Як створити Telegram-бота: гайд для початківців',
    title: 'Як створити Telegram-бота: покроковий гайд',
    description:
      'Покрокова інструкція TeleBots: BotFather, Python, python-telegram-bot, хостинг і перші команди. Запустіть свого Telegram-бота без зайвої теорії.',
    keywords: 'як створити телеграм бота, telegram bot tutorial, python telegram bot, BotFather',
    excerpt:
      'Повний гайд для початківців: від реєстрації в BotFather до деплою бота на сервер. З прикладами коду та best practices.',
  },
  {
    slug: 'integratsiya-telegram-botiv',
    legacyId: 2,
    category: 'telegram',
    publishedAt: '2025-11-05',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 16,
    image: legacyBlogImages[2],
    imageAlt: 'MacBook з інтерфейсом розробника',
    relatedSlugs: [
      'telegram-bot-dlya-biznesu-2026',
      'platizhni-systemy-v-telegram-boti',
      'rozrobka-telegram-botiv-vid-ideyi',
      'skilky-koshtuye-telegram-bot',
    ],
    seoTitle: 'Інтеграція Telegram-ботів з CRM і API',
    title: 'Інтеграція Telegram-ботів з іншими сервісами',
    description:
      'Підключіть бота до Google Sheets, CRM, Slack, платежів і власного API. Практичні приклади інтеграцій від TeleBots без втрати даних і з автоматизацією.',
    keywords: 'інтеграція телеграм бота, google sheets bot, crm telegram, webhook telegram',
    excerpt: 'Як з’єднати бота з таблицями, CRM і зовнішніми API — без втрати даних і з автоматизацією процесів.',
  },
  {
    slug: 'rozrobka-telegram-botiv-vid-ideyi',
    legacyId: 3,
    category: 'telegram',
    publishedAt: '2025-11-10',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 14,
    image: legacyBlogImages[3],
    imageAlt: 'Робоче місце розробника, деталі клавіатури',
    relatedSlugs: ['telegram-bot-dlya-biznesu-2026', 'skilky-koshtuye-telegram-bot', 'yak-stvoryty-telegram-bota'],
    title: 'Професійна розробка Telegram ботів: від ідеї до продакшену',
    description:
      'Етапи розробки бота під ключ: ТЗ, архітектура, код, тести, Docker, моніторинг і підтримка. Досвід TeleBots.',
    keywords: 'розробка телеграм бота під ключ, замовити бота, telegram bot development',
    excerpt: 'Від брифу до продакшену: як будується професійний бот і що очікувати від підрядника.',
  },
  {
    slug: 'voronky-prodazhiv-telegram',
    legacyId: 4,
    category: 'business',
    publishedAt: '2025-11-12',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 12,
    image: legacyBlogImages[4],
    imageAlt: 'Преміум-абстракція для маркетингу та воронок продажів',
    relatedSlugs: ['telegram-bot-dlya-biznesu-2026', 'skilky-koshtuye-telegram-bot', 'zbit-lidiv-telegram-bot'],
    title: 'Створення ефективних воронок продажів з Telegram ботами',
    description:
      'Як побудувати воронку в Telegram: залучення, прогрів, оплата, аналітика кроків і повторні продажі.',
    keywords: 'воронка продажів telegram, продажі в боті, чат-бот воронка',
    excerpt: 'Покрокова воронка в месенджері — від першого /start до оплати та допродажів.',
  },
  {
    slug: 'platizhni-systemy-v-telegram-boti',
    legacyId: 5,
    category: 'telegram',
    publishedAt: '2025-11-15',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 13,
    image: legacyBlogImages[5],
    imageAlt: 'Ділова естетика: робочий стіл з гаджетами',
    relatedSlugs: ['telegram-bot-dlya-biznesu-2026', 'skilky-koshtuye-telegram-bot', 'monetizatsiya-telegram-botiv'],
    title: 'Інтеграція платіжних систем у Telegram ботах',
    description:
      'Mono, LiqPay, WayForPay у боті: прийом оплати, webhooks, безпека та UX для користувача в Україні.',
    keywords: 'оплата в телеграм боті, liqpay bot, monopay telegram, платіжна система бот',
    excerpt: 'Приймайте оплату прямо в чаті — без зайвих переходів і з підтвердженням транзакцій.',
  },
  {
    slug: 'suchasni-veb-sajty-rozrobka',
    legacyId: 6,
    category: 'websites',
    publishedAt: '2025-11-18',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 15,
    image: legacyBlogImages[6],
    imageAlt: 'Розробка веб-сайтів на MacBook',
    seoTitle: 'Розробка сучасних веб-сайтів у 2026 році',
    title: 'Професійна розробка сучасних веб-сайтів',
    relatedSlugs: [
      'skilky-koshtuye-sayt',
      'skilky-koshtuye-internet-mahazyn',
      'telegram-bot-dlya-biznesu-2026',
    ],
    description:
      'Next.js, SEO, швидкість, адаптив і Core Web Vitals: як має виглядати сучасний сайт для бізнесу в 2026. Гайд TeleBots від структури до запуску.',
    keywords: 'розробка сучасного сайту, next.js сайт, seo сайт, веб-розробка',
    excerpt: 'Технології, етапи та вимоги до сайту, який конвертує відвідувачів у заявки.',
  },
  {
    slug: 'prodazhi-loyalnist-telegram-bot',
    legacyId: 7,
    category: 'business',
    publishedAt: '2025-11-20',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 14,
    image: legacyBlogImages[7],
    imageAlt: 'Сучасна студія digital-агенції',
    seoTitle: 'Продажі та лояльність клієнтів через Telegram-ботів',
    title: 'Як збільшити продажі та лояльність через Telegram-боти',
    relatedSlugs: [
      'telegram-bot-dlya-biznesu-2026',
      'voronky-prodazhiv-telegram',
      'zbit-lidiv-telegram-bot',
      'monetizatsiya-telegram-botiv',
    ],
    description:
      'Автоматизація підтримки, програми лояльності, розсилки та CRM у Telegram-боті. Як повертати клієнтів і зростати продажі 24/7 — гайд TeleBots.',
    keywords: 'продажі telegram bot, лояльність клієнтів бот, автоматизація продажів',
    excerpt: 'Бот працює 24/7: підтримка, нагадування, бонуси та повернення клієнтів.',
  },
  {
    slug: 'zbir-analiz-danyh-telegram',
    legacyId: 8,
    category: 'business',
    publishedAt: '2025-11-22',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 17,
    image: legacyBlogImages[8],
    imageAlt: 'Концепт нейромережі та аналітики даних',
    seoTitle: 'Збір та аналіз даних через Telegram-ботів',
    title: 'Збір та аналіз даних через Telegram ботів: комплексний посібник',
    description:
      'Опитування, метрики, експорт у Sheets і BI. Як перетворити дані з бота на рішення для бізнесу.',
    keywords: 'аналітика telegram bot, опитування в боті, збір даних telegram',
    excerpt: 'Від збору відгуків до дашбордів — практичний посібник з аналітики в боті.',
  },
  {
    slug: 'shtuchnyi-intelekt-v-telegram-boti',
    legacyId: 9,
    category: 'ai',
    publishedAt: '2025-11-25',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 16,
    image: legacyBlogImages[9],
    imageAlt: '3D-абстракція потоків даних та штучного інтелекту',
    relatedSlugs: ['telegram-bot-dlya-biznesu-2026', 'ai-telegram-posibnyk', 'skilky-koshtuye-telegram-bot'],
    seoTitle: 'Штучний інтелект у Telegram-ботах: інтеграція',
    title: 'Інтеграція штучного інтелекту в Telegram боти: повний посібник',
    description:
      'GPT, API, промпти, модерація та вартість токенів. Як безпечно додати ШІ в бота для бізнесу.',
    keywords: 'gpt telegram bot, ai чат бот, штучний інтелект бот, openai telegram',
    excerpt: 'Підключення LLM до бота: сценарії, обмеження та контроль якості відповідей.',
  },
  {
    slug: 'bezpeka-telegram-botiv',
    legacyId: 10,
    category: 'security',
    publishedAt: '2025-11-28',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 15,
    image: legacyBlogImages[10],
    imageAlt: 'Неонова підсвітка коду — безпека та хай-тек',
    relatedSlugs: [
      'yak-stvoryty-telegram-bota',
      'rozrobka-telegram-botiv-vid-ideyi',
      'telegram-bot-dlya-biznesu-2026',
      'integratsiya-telegram-botiv',
    ],
    seoTitle: 'Безпека Telegram-ботів у 2026: чеклист захисту',
    title: 'Безпека Telegram-ботів: захист даних та користувачів',
    description:
      'Токени, HTTPS webhook, GDPR, rate limiting і чеклист безпеки Telegram-бота. Гайд TeleBots для розробників і бізнесу без витоків даних.',
    keywords: 'безпека telegram bot, захист даних бот, webhook security',
    excerpt: 'Комплексний посібник: як не втратити токен і не злити дані клієнтів.',
  },
  {
    slug: 'ai-telegram-posibnyk',
    legacyId: 11,
    category: 'ai',
    publishedAt: '2025-12-01',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 12,
    image: legacyBlogImages[11],
    imageAlt: 'Кібернетична абстракція штучного інтелекту',
    title: 'Штучний інтелект в Telegram ботах: повний посібник',
    description:
      'NLP, персоналізація, GPT і гібридні сценарії — як впровадити ШІ без шкоди для бренду.',
    keywords: 'штучний інтелект telegram, ai bot business, nlp telegram',
    excerpt: 'ШІ + сценарії: передбачувані відповіді та ескалація на людину.',
  },
  {
    slug: 'zbit-lidiv-telegram-bot',
    legacyId: 12,
    category: 'business',
    publishedAt: '2025-12-05',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 11,
    image: legacyBlogImages[12],
    imageAlt: 'Взаємодія людини та технологій',
    relatedSlugs: ['telegram-bot-dlya-biznesu-2026', 'voronky-prodazhiv-telegram', 'skilky-koshtuye-telegram-bot'],
    title: 'Збір лідів через Telegram ботів: повний посібник',
    description:
      'Лід-магніти, квізи, UTM і передача заявок у CRM. Зниження вартості ліда з реклами.',
    keywords: 'ліди telegram bot, збір заявок бот, lead generation telegram',
    excerpt: 'Квізи, чеклисти та форми в боті — що реально конвертує з реклами.',
  },
  {
    slug: 'monetizatsiya-telegram-botiv',
    legacyId: 13,
    category: 'business',
    publishedAt: '2025-12-08',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 12,
    image: legacyBlogImages[13],
    imageAlt: 'Преміум-робоче місце для бізнесу та монетизації',
    title: 'Монетизація Telegram ботів: повний посібник',
    description:
      'Підписки, разові платежі, freemium і B2B-моделі — як заробляти на боті в 2026.',
    keywords: 'монетизація telegram bot, заробіток на боті, підписка telegram',
    excerpt: 'Огляд моделей доходу та що обрати під вашу аудиторію.',
  },
  {
    slug: 'parsing-danyh-telegram-bot',
    legacyId: 14,
    category: 'business',
    publishedAt: '2025-12-10',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 13,
    image: legacyBlogImages[14],
    imageAlt: 'Цифрова архітектура систем та автоматизація',
    relatedSlugs: [
      'zbir-analiz-danyh-telegram',
      'telegram-bot-dlya-biznesu-2026',
      'skilky-koshtuye-telegram-bot',
    ],
    seoTitle: 'Парсинг даних через Telegram-ботів: гайд',
    title: 'Парсинг даних через Telegram-ботів',
    description:
      'Збір цін, каталогів і оголошень через Telegram-бота: етичний парсинг, ліміти платформ і автоматизація. Коли парсер потрібен і як інтегрувати дані.',
    keywords: 'парсер даних, парсинг telegram, автоматизація збору даних',
    excerpt: 'Коли парсер потрібен бізнесу і як не порушити правила платформ.',
  },
  {
    slug: 'perspektyvy-telegram-botiv-ukraina',
    legacyId: 15,
    category: 'business',
    publishedAt: '2025-12-15',
    updatedAt: '2026-05-25',
    readingTimeMinutes: 10,
    image: legacyBlogImages[15],
    imageAlt: 'Мінімалістична архітектура — масштаб і надійність бізнесу',
    seoTitle: 'Telegram-боти в Україні: аналіз ринку та прогнози',
    title: 'Перспективи Telegram-ботів в Україні на 2026–2027',
    relatedSlugs: [
      'telegram-bot-dlya-biznesu-2026',
      'monetizatsiya-telegram-botiv',
      'ai-telegram-posibnyk',
      'zbit-lidiv-telegram-bot',
    ],
    description:
      'Ринок месенджерів, e-commerce, EdTech і держсектор в Україні: куди рухається індустрія Telegram-ботів у 2026–2027. Тренди та можливості для бізнесу.',
    keywords: 'telegram боти україна, тренди telegram 2026, ринок ботів',
    excerpt: 'Тренди та можливості для бізнесу й розробників на українському ринку.',
  },
];

export function getLegacyHeroImage(legacyId: number): string {
  return legacyBlogImages[legacyId] ?? legacyBlogImages[1];
}
